version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    # use docker compose to watch for changes and rebuild the container
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: ./pnpm-lock.yaml
          action: rebuild
        - path: .
          target: /app
          action: sync

  postgres:
    image: postgres:15-alpine

    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
